### ISSUE TITLE
Upgrade to Gateway API v1.0

### ISSUE THREAD

**Issue by davidkornel** [l7mp/stunner-gateway-operator#37]
In the latest versions of Kubernetes the deprecated v1alpha2 API has been removed definitively. I cannot provide any docs but I hope to find some exact details. I gathered this information from the Kubernetes Slack channel.
![image](https://github.com/l7mp/stunner-gateway-operator/assets/47784437/4822202b-2794-43c8-9dea-484ef60e7e36)

This error is raised only when the gateway class and gateway are being updated. Not sure @rg0now  if you know about this but it doesn't matter what API version we create the resources with. It will be overwritten on the first upgrade event from the operator. [In this line](https://github.com/l7mp/stunner-gateway-operator/blob/dab0dcc79afdfc41f2ec44e225c6d1a98111083f/internal/controllers/gateway.go#L146) the API version will be ignored and will be set to v1alpha2 and used further on during the whole process.

The main problem that this raises is that the operator won't be able to run on the latest versions of k8s.

**Comment by rg0now** [comment]
I'm not sure it's a Kubernetes issue, I'd rather say it's most probably GKE advancing really fast. That being said, this will need to be fixed before the new release: our GatewayClass and Gateway must be upgraded to v1beta1. The idea is that every time we [create](https://github.com/l7mp/stunner-gateway-operator/blob/768d073ca976a2c7a933f4f5b8132fa328cdfb65/internal/renderer/gateway_util.go#L28)/manage/delete/[watch](https://github.com/l7mp/stunner-gateway-operator/blob/768d073ca976a2c7a933f4f5b8132fa328cdfb65/internal/controllers/gateway.go#L79) any Gateway API resource we must update the package version from v1alpha2 to v1beta1. This will be a PITA because all the zillions places in the code and the tests where we refer to a Gateway or GatewayClass the reference will have to be updated. AFAIK UDPRoutes have not migrated to v1beta1 (yet?), so only GatewayClass and Gateway are affected. Any takers?

**Comment by rg0now** [comment]
With the Gateway API going GA, we should repurpose this issue to move the operator to the Gateway API v1.0.

**Comment by davidkornel** [comment]
Another fact that hurries us to upgrade is that some Gateway API users, e.g., Envoy-gateway, are already using the v1.0 API which is not compatible with our current state.

**Comment by levaitamas** [comment]
Done in [v0.17.0](https://github.com/l7mp/stunner/releases/tag/v0.17.0).
