### ISSUE TITLE
Gateway CRD deployment

### ISSUE THREAD

**Issue by joaogbcravo** [l7mp/stunner-gateway-operator#40]
I noticed this operator deploys some CRDs for gateway-API but not all of them (for example HTTPRoute). Is there a reason for that?

This can affect other workloads that also install the CRDs or that require all the CRDs when some feature flag is activated.

I propose to have a feature flag to trigger the CRDs installation OR add all the CRDs found at https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.6.2/standard-install.yaml.

I am happy to do the PR if you agree with one of those.

**Comment by davidkornel** [comment]
Hi @joaogbcravo 

You are correct; we are not installing all the gateway-API CRDs, only a few of them that we use in the STUNner gateway operator. This issue came up last week in this [PR](https://github.com/l7mp/stunner-helm/pull/17). IMO, once we upgraded all the Go imports and the CRDs to their latest version, we can add all the CRDs to the helm chart.

@rg0now in the linked PR you haven't shared your opinion about adding the missing CRDs. Do you think we should install them even though not using them at all? Unfortunately, Helm [does not support templating the CRDs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#:~:text=Another%20important%20point,of%20the%20cluster.) so we cannot create an enabler flag or some sort of switch to enable or disable the installation of the extra CRDs. This means we have to either install all of them or not support them.

**Comment by rg0now** [comment]
Thanks for the offer. I think you're right: maybe it's not that good idea after all to selectively install only the CRDs that we use because we may clash with other Gateway API implementations. We chose this originally because the Gateway API is fairly huge, but in retrospect this does not seem to be that much of a good idea...

 @davidkornel care to do the change?

**Comment by davidkornel** [comment]
Yes I will handle it

**Comment by davidkornel** [comment]
@joaogbcravo In the latest commit all the latest CRDs have been added to this repo. Also, they've been merged into the Helm chart https://github.com/l7mp/stunner-helm/pull/17

May I ask you what are you working on? We are interested in all the use cases as we care about our users and their situations. If you wish to explain it we would be glad for your help. 
And don't forget to join our Discord as it is easier to have a talk there:
https://discord.com/invite/DyPgEsbwzc

**Comment by rg0now** [comment]
Fixed as of l7mp/stunner-helm#17
